fixtures:
  repositories:
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
    cron_core:
      repo: https://github.com/puppetlabs/puppetlabs-cron_core.git
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    logrotate:
      repo: https://github.com/voxpupuli/puppet-logrotate.git
    epel:
      repo: https://github.com/voxpupuli/puppet-epel.git
    mysql: 
      repo: https://github.com/puppetlabs/puppetlabs-mysql.git
    mongodb:
      repo: https://github.com/puppetlabs/puppetlabs-mongodb.git
    inifile:
      repo: https://github.com/puppetlabs/puppetlabs-inifile
    apache:
      repo: https://github.com/puppetlabs/puppetlabs-apache
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat.git
    archive:
      repo: https://github.com/voxpupuli/puppet-archive
    yum:
      repo: https://github.com/voxpupuli/puppet-yum.git
    augeasproviders_core:
      repo: https://github.com/hercules-team/augeasproviders_core
    augeasproviders_shellvar:
      repo: https://github.com/hercules-team/augeasproviders_shellvar
    pcp:
      repo: https://github.com/treydock/puppet-module-pcp.git
    sudo:
      repo: https://github.com/saz/puppet-sudo.git
    openssl:
      repo: https://github.com/camptocamp/puppet-openssl
    geoip:
      repo: https://github.com/rtib/puppet-geoip
    # Needed by geoip
    systemd:
      repo: https://github.com/camptocamp/puppet-systemd
  symlinks:
    xdmod: "#{source_dir}"
