fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
    cron_core:
      repo: puppetlabs/cron_core
    logrotate:
      repo: puppet/logrotate
    epel:
      repo: puppet/epel
    mysql: 
      repo: puppetlabs/mysql
    mongodb:
      repo: puppet/mongodb
    inifile:
      repo: puppetlabs/inifile
    apache:
      repo: puppetlabs/apache
    concat:
      repo: puppetlabs/concat
    archive:
      repo: puppet/archive
    yum:
      repo: puppet/yum
    augeasproviders_core:
      repo: puppet/augeasproviders_core
    augeasproviders_shellvar:
      repo: puppet/augeasproviders_shellvar
    pcp:
      repo: treydock/pcp
    sudo:
      repo: saz/sudo
    openssl:
      repo: puppet/openssl
    geoip:
      repo: trepasi/geoip
    # Needed by geoip
    systemd:
      repo: puppet/systemd
    php:
      repo: puppet/php
  symlinks:
    xdmod: "#{source_dir}"
